---
- name: Get version from facts
  hosts: csr
  gather_facts: no
  connection: local
  tasks:
    - name: Get hardware facts
      ios_facts:
         gather_subset: interfaces
         provider:
               username: "{{ username }}"
               password: "{{ password }}"
               port: "{{ port }}"
               host: "{{ ansible_host }}"
               timeout: 30
      register: interfaces
    - name: Print
      debug:  
         msg: "{{ interfaces }}" 

